import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#263143",
        "on-secondary": "#293041",
        "on-primary-fixed-variant": "#005321",
        "inverse-primary": "#006e2f",
        "on-primary": "#003915",
        "on-error": "#690005",
        "surface-container": "#1d2022",
        primary: "#4be277",
        "secondary-fixed-dim": "#c0c6db",
        "on-tertiary-fixed": "#111c2d",
        "tertiary-fixed-dim": "#bcc7de",
        "surface-tint": "#4ae176",
        "secondary-fixed": "#dce2f8",
        "on-primary-container": "#004b1e",
        "on-background": "#e0e3e5",
        "surface-variant": "#323537",
        outline: "#869585",
        "on-error-container": "#ffdad6",
        "secondary-container": "#42495a",
        "surface-container-high": "#272a2c",
        background: "#101415",
        surface: "#101415",
        "primary-fixed-dim": "#4ae176",
        "surface-container-low": "#191c1e",
        "surface-dim": "#101415",
        "on-surface": "#e0e3e5",
        "inverse-surface": "#e0e3e5",
        "inverse-on-surface": "#2d3133",
        "on-secondary-container": "#b2b8cd",
        "tertiary-container": "#a1acc3",
        secondary: "#c0c6db",
        "tertiary-fixed": "#d8e3fb",
        "primary-container": "#22c55e",
        "on-secondary-fixed": "#151b2b",
        "outline-variant": "#3d4a3d",
        "error-container": "#93000a",
        error: "#ffb4ab",
        "on-secondary-fixed-variant": "#404758",
        "on-surface-variant": "#bccbb9",
        "on-tertiary-fixed-variant": "#3c475a",
        "on-tertiary-container": "#354053",
        tertiary: "#bcc7df",
        "surface-bright": "#363a3b",
        "surface-container-highest": "#323537",
        "on-primary-fixed": "#002109",
        "surface-container-lowest": "#0b0f10",
        "primary-fixed": "#6bff8f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        md: "24px",
        margin: "24px",
        gutter: "16px",
        xs: "4px",
        xl: "80px",
        lg: "48px",
        sm: "12px",
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg": [
          "32px",
          {
            lineHeight: "1.2",
            letterSpacing: "-0.01em",
            fontWeight: "700",
          },
        ],
        "label-bold": [
          "14px",
          { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-xl": [
          "48px",
          {
            lineHeight: "1.1",
            letterSpacing: "-0.02em",
            fontWeight: "800",
          },
        ],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
